# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: PR - Serverless Service CI/CD

permissions:
  contents: read

env:
  NODE_VERSION: "20"
  PYTHON_VERSION: "3.12"
  AWS_REGION: "us-east-1"

on:
  workflow_dispatch:

  pull_request:
    branches: [main]

jobs:
  quality_standards:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was automatically triggered by a ${{ env.EVENT_NAME }} event." >> $GITHUB_STEP_SUMMARY
          echo "🐧 This job is now running on a ${{ env.OS_NAME }} ${{env.OS_ARCH}} server hosted by GitHub!" >> $GITHUB_STEP_SUMMARY
          echo "🔎 The name of your branch is ${{ env.BRANCH_NAME }} and your repository is ${{ env.REPO_NAME }}." >> $GITHUB_STEP_SUMMARY
        env:
          EVENT_NAME: ${{ github.event_name}}
          OS_NAME: ${{ runner.os }}
          OS_ARCH: ${{runner.arch }}
          BRANCH_NAME: ${{ github.ref }}
          REPO_NAME: ${{ github.repository }}
      - name: Check out repository code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "poetry" # NOTE: poetry must be installed before this step, or else cache doesn't work
      - name: Install dependencies
        run: make dev
      - name: pre commit
        run: make pre-commit
      - name: Formatting and Linting
        run: make lint
      - name: Complexity scan
        run: make complex
